echo "$FORTRAN $FFLAGS ./anal/anal_energy.f -o objects/anal_energy.o"; $FORTRAN $FFLAGS ./anal/anal_energy.f -o objects/anal_energy.o
echo "$FORTRAN $FFLAGS ./anal/anal_energy_write.f -o objects/anal_energy_write.o"; $FORTRAN $FFLAGS ./anal/anal_energy_write.f -o objects/anal_energy_write.o
echo "$FORTRAN $FFLAGS ./anal/anal_jacobi.f -o objects/anal_jacobi.o"; $FORTRAN $FFLAGS ./anal/anal_jacobi.f -o objects/anal_jacobi.o
echo "$FORTRAN $FFLAGS ./anal/anal_jacobi_write.f -o objects/anal_jacobi_write.o"; $FORTRAN $FFLAGS ./anal/anal_jacobi_write.f -o objects/anal_jacobi_write.o
echo "$FORTRAN $FFLAGS ./bs/bs_der.f -o objects/bs_der.o"; $FORTRAN $FFLAGS ./bs/bs_der.f -o objects/bs_der.o
echo "$FORTRAN $FFLAGS ./bs/bs_int.f -o objects/bs_int.o"; $FORTRAN $FFLAGS ./bs/bs_int.f -o objects/bs_int.o
echo "$FORTRAN $FFLAGS ./bs/bs_step.f -o objects/bs_step.o"; $FORTRAN $FFLAGS ./bs/bs_step.f -o objects/bs_step.o
echo "$FORTRAN $FFLAGS ./coord/coord_b2h.f -o objects/coord_b2h.o"; $FORTRAN $FFLAGS ./coord/coord_b2h.f -o objects/coord_b2h.o
echo "$FORTRAN $FFLAGS ./coord/coord_b2h_tp.f -o objects/coord_b2h_tp.o"; $FORTRAN $FFLAGS ./coord/coord_b2h_tp.f -o objects/coord_b2h_tp.o
echo "$FORTRAN $FFLAGS ./coord/coord_b2j.f -o objects/coord_b2j.o"; $FORTRAN $FFLAGS ./coord/coord_b2j.f -o objects/coord_b2j.o
echo "$FORTRAN $FFLAGS ./coord/coord_h2b.f -o objects/coord_h2b.o"; $FORTRAN $FFLAGS ./coord/coord_h2b.f -o objects/coord_h2b.o
echo "$FORTRAN $FFLAGS ./coord/coord_h2b_tp.f -o objects/coord_h2b_tp.o"; $FORTRAN $FFLAGS ./coord/coord_h2b_tp.f -o objects/coord_h2b_tp.o
echo "$FORTRAN $FFLAGS ./coord/coord_h2j.f -o objects/coord_h2j.o"; $FORTRAN $FFLAGS ./coord/coord_h2j.f -o objects/coord_h2j.o
echo "$FORTRAN $FFLAGS ./coord/coord_j2b.f -o objects/coord_j2b.o"; $FORTRAN $FFLAGS ./coord/coord_j2b.f -o objects/coord_j2b.o
echo "$FORTRAN $FFLAGS ./coord/coord_j2h.f -o objects/coord_j2h.o"; $FORTRAN $FFLAGS ./coord/coord_j2h.f -o objects/coord_j2h.o
echo "$FORTRAN $FFLAGS ./coord/coord_vb2h.f -o objects/coord_vb2h.o"; $FORTRAN $FFLAGS ./coord/coord_vb2h.f -o objects/coord_vb2h.o
echo "$FORTRAN $FFLAGS ./coord/coord_vb2h_tp.f -o objects/coord_vb2h_tp.o"; $FORTRAN $FFLAGS ./coord/coord_vb2h_tp.f -o objects/coord_vb2h_tp.o
echo "$FORTRAN $FFLAGS ./coord/coord_vh2b.f -o objects/coord_vh2b.o"; $FORTRAN $FFLAGS ./coord/coord_vh2b.f -o objects/coord_vh2b.o
echo "$FORTRAN $FFLAGS ./coord/coord_vh2b_tp.f -o objects/coord_vh2b_tp.o"; $FORTRAN $FFLAGS ./coord/coord_vh2b_tp.f -o objects/coord_vh2b_tp.o
echo "$FORTRAN $FFLAGS ./coord/coord_vh2vj.f -o objects/coord_vh2vj.o"; $FORTRAN $FFLAGS ./coord/coord_vh2vj.f -o objects/coord_vh2vj.o
echo "$FORTRAN $FFLAGS ./discard/discard.f -o objects/discard.o"; $FORTRAN $FFLAGS ./discard/discard.f -o objects/discard.o
echo "$FORTRAN $FFLAGS ./discard/discard_mass_merge.f -o objects/discard_mass_merge.o"; $FORTRAN $FFLAGS ./discard/discard_mass_merge.f -o objects/discard_mass_merge.o
echo "$FORTRAN $FFLAGS ./discard/discard_mass_peri.f -o objects/discard_mass_peri.o"; $FORTRAN $FFLAGS ./discard/discard_mass_peri.f -o objects/discard_mass_peri.o
echo "$FORTRAN $FFLAGS ./discard/discard_mass_reorder.f -o objects/discard_mass_reorder.o"; $FORTRAN $FFLAGS ./discard/discard_mass_reorder.f -o objects/discard_mass_reorder.o
echo "$FORTRAN $FFLAGS ./discard/discard_massive.f -o objects/discard_massive.o"; $FORTRAN $FFLAGS ./discard/discard_massive.f -o objects/discard_massive.o
echo "$FORTRAN $FFLAGS ./discard/discard_peri.f -o objects/discard_peri.o"; $FORTRAN $FFLAGS ./discard/discard_peri.f -o objects/discard_peri.o
echo "$FORTRAN $FFLAGS ./discard/discard_pl.f -o objects/discard_pl.o"; $FORTRAN $FFLAGS ./discard/discard_pl.f -o objects/discard_pl.o
echo "$FORTRAN $FFLAGS ./discard/discard_pl_close.f -o objects/discard_pl_close.o"; $FORTRAN $FFLAGS ./discard/discard_pl_close.f -o objects/discard_pl_close.o
echo "$FORTRAN $FFLAGS ./discard/discard_sun.f -o objects/discard_sun.o"; $FORTRAN $FFLAGS ./discard/discard_sun.f -o objects/discard_sun.o
echo "$FORTRAN $FFLAGS ./io/io_discard_mass.f -o objects/io_discard_mass.o"; $FORTRAN $FFLAGS ./io/io_discard_mass.f -o objects/io_discard_mass.o
echo "$FORTRAN $FFLAGS ./io/io_discard_merge.f -o objects/io_discard_merge.o"; $FORTRAN $FFLAGS ./io/io_discard_merge.f -o objects/io_discard_merge.o
echo "$FORTRAN $FFLAGS ./io/io_discard_write.f -o objects/io_discard_write.o"; $FORTRAN $FFLAGS ./io/io_discard_write.f -o objects/io_discard_write.o
echo "$FORTRAN $FFLAGS ./io/io_dump_param.f -o objects/io_dump_param.o"; $FORTRAN $FFLAGS ./io/io_dump_param.f -o objects/io_dump_param.o
echo "$FORTRAN $FFLAGS ./io/io_dump_pl.f -o objects/io_dump_pl.o"; $FORTRAN $FFLAGS ./io/io_dump_pl.f -o objects/io_dump_pl.o
echo "$FORTRAN $FFLAGS ./io/io_dump_pl_symba.f -o objects/io_dump_pl_symba.o"; $FORTRAN $FFLAGS ./io/io_dump_pl_symba.f -o objects/io_dump_pl_symba.o
echo "$FORTRAN $FFLAGS ./io/io_dump_tp.f -o objects/io_dump_tp.o"; $FORTRAN $FFLAGS ./io/io_dump_tp.f -o objects/io_dump_tp.o
echo "$FORTRAN $FFLAGS ./io/io_energy_write.f -o objects/io_energy_write.o"; $FORTRAN $FFLAGS ./io/io_energy_write.f -o objects/io_energy_write.o
echo "$FORTRAN $FFLAGS ./io/io_getns.f -o objects/io_getns.o"; $FORTRAN $FFLAGS ./io/io_getns.f -o objects/io_getns.o
echo "$FORTRAN $FFLAGS ./io/io_init_param.f -o objects/io_init_param.o"; $FORTRAN $FFLAGS ./io/io_init_param.f -o objects/io_init_param.o
echo "$FORTRAN $FFLAGS ./io/io_init_pl.f -o objects/io_init_pl.o"; $FORTRAN $FFLAGS ./io/io_init_pl.f -o objects/io_init_pl.o
echo "$FORTRAN $FFLAGS ./io/io_init_pl_symba.f -o objects/io_init_pl_symba.o"; $FORTRAN $FFLAGS ./io/io_init_pl_symba.f -o objects/io_init_pl_symba.o
echo "$FORTRAN $FFLAGS ./io/io_init_tp.f -o objects/io_init_tp.o"; $FORTRAN $FFLAGS ./io/io_init_tp.f -o objects/io_init_tp.o
echo "$FORTRAN $FFLAGS ./io/io_jacobi_write.f -o objects/io_jacobi_write.o"; $FORTRAN $FFLAGS ./io/io_jacobi_write.f -o objects/io_jacobi_write.o
echo "$FORTRAN $FFLAGS ./io/io_lyap2_write.f -o objects/io_lyap2_write.o"; $FORTRAN $FFLAGS ./io/io_lyap2_write.f -o objects/io_lyap2_write.o
echo "$FORTRAN $FFLAGS ./io/io_lyap_init.f -o objects/io_lyap_init.o"; $FORTRAN $FFLAGS ./io/io_lyap_init.f -o objects/io_lyap_init.o
echo "$FORTRAN $FFLAGS ./io/io_lyap_write.f -o objects/io_lyap_write.o"; $FORTRAN $FFLAGS ./io/io_lyap_write.f -o objects/io_lyap_write.o
echo "$FORTRAN $FFLAGS ./io/io_mvits_init.f -o objects/io_mvits_init.o"; $FORTRAN $FFLAGS ./io/io_mvits_init.f -o objects/io_mvits_init.o
echo "$FORTRAN $FFLAGS ./io/io_open_CPP.f -o objects/io_open_CPP.o"; $FORTRAN $FFLAGS ./io/io_open_CPP.f -o objects/io_open_CPP.o
echo "$FORTRAN $FFLAGS ./io/io_read_hdr.f -o objects/io_read_hdr.o"; $FORTRAN $FFLAGS ./io/io_read_hdr.f -o objects/io_read_hdr.o
echo "$FORTRAN $FFLAGS ./io/io_read_hdr_r.f -o objects/io_read_hdr_r.o"; $FORTRAN $FFLAGS ./io/io_read_hdr_r.f -o objects/io_read_hdr_r.o
echo "$FORTRAN $FFLAGS ./io/io_read_line.f -o objects/io_read_line.o"; $FORTRAN $FFLAGS ./io/io_read_line.f -o objects/io_read_line.o
echo "$FORTRAN $FFLAGS ./io/io_read_line_r.f -o objects/io_read_line_r.o"; $FORTRAN $FFLAGS ./io/io_read_line_r.f -o objects/io_read_line_r.o
echo "$FORTRAN $FFLAGS ./io/io_read_mass.f -o objects/io_read_mass.o"; $FORTRAN $FFLAGS ./io/io_read_mass.f -o objects/io_read_mass.o
echo "$FORTRAN $FFLAGS ./io/io_splitname.f -o objects/io_splitname.o"; $FORTRAN $FFLAGS ./io/io_splitname.f -o objects/io_splitname.o
echo "$FORTRAN $FFLAGS ./io/io_write_frame.f -o objects/io_write_frame.o"; $FORTRAN $FFLAGS ./io/io_write_frame.f -o objects/io_write_frame.o
echo "$FORTRAN $FFLAGS ./io/io_write_frame_r.f -o objects/io_write_frame_r.o"; $FORTRAN $FFLAGS ./io/io_write_frame_r.f -o objects/io_write_frame_r.o
echo "$FORTRAN $FFLAGS ./io/io_write_hdr.f -o objects/io_write_hdr.o"; $FORTRAN $FFLAGS ./io/io_write_hdr.f -o objects/io_write_hdr.o
echo "$FORTRAN $FFLAGS ./io/io_write_hdr_r.f -o objects/io_write_hdr_r.o"; $FORTRAN $FFLAGS ./io/io_write_hdr_r.f -o objects/io_write_hdr_r.o
echo "$FORTRAN $FFLAGS ./io/io_write_line.f -o objects/io_write_line.o"; $FORTRAN $FFLAGS ./io/io_write_line.f -o objects/io_write_line.o
echo "$FORTRAN $FFLAGS ./io/io_write_line_r.f -o objects/io_write_line_r.o"; $FORTRAN $FFLAGS ./io/io_write_line_r.f -o objects/io_write_line_r.o
echo "$FORTRAN $FFLAGS ./io/io_write_mass.f -o objects/io_write_mass.o"; $FORTRAN $FFLAGS ./io/io_write_mass.f -o objects/io_write_mass.o
echo "$FORTRAN $FFLAGS ./lyap/lyap_renorm.f -o objects/lyap_renorm.o"; $FORTRAN $FFLAGS ./lyap/lyap_renorm.f -o objects/lyap_renorm.o
echo "$FORTRAN $FFLAGS ./lyap/lyap_step.f -o objects/lyap_step.o"; $FORTRAN $FFLAGS ./lyap/lyap_step.f -o objects/lyap_step.o
echo "$FORTRAN $FFLAGS ./lyap/lyap_step_sh.f -o objects/lyap_step_sh.o"; $FORTRAN $FFLAGS ./lyap/lyap_step_sh.f -o objects/lyap_step_sh.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_acc_tp.f -o objects/lyap2_acc_tp.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_acc_tp.f -o objects/lyap2_acc_tp.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_drift_dan.f -o objects/lyap2_drift_dan.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_drift_dan.f -o objects/lyap2_drift_dan.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_drift_kepu.f -o objects/lyap2_drift_kepu.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_drift_kepu.f -o objects/lyap2_drift_kepu.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_drift_one.f -o objects/lyap2_drift_one.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_drift_one.f -o objects/lyap2_drift_one.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_drift_tp.f -o objects/lyap2_drift_tp.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_drift_tp.f -o objects/lyap2_drift_tp.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_kepu_mikk.f -o objects/lyap2_kepu_mikk.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_kepu_mikk.f -o objects/lyap2_kepu_mikk.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_step.f -o objects/lyap2_step.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_step.f -o objects/lyap2_step.o
echo "$FORTRAN $FFLAGS ./lyap2/lyap2_step_tp.f -o objects/lyap2_step_tp.o"; $FORTRAN $FFLAGS ./lyap2/lyap2_step_tp.f -o objects/lyap2_step_tp.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_getacch_tp.f -o objects/mvits_getacch_tp.o"; $FORTRAN $FFLAGS ./mvits/mvits_getacch_tp.f -o objects/mvits_getacch_tp.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_init_rot.f -o objects/mvits_init_rot.o"; $FORTRAN $FFLAGS ./mvits/mvits_init_rot.f -o objects/mvits_init_rot.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_kickvh_tp.f -o objects/mvits_kickvh_tp.o"; $FORTRAN $FFLAGS ./mvits/mvits_kickvh_tp.f -o objects/mvits_kickvh_tp.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_lstep_tp.f -o objects/mvits_lstep_tp.o"; $FORTRAN $FFLAGS ./mvits/mvits_lstep_tp.f -o objects/mvits_lstep_tp.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_obl_kick.f -o objects/mvits_obl_kick.o"; $FORTRAN $FFLAGS ./mvits/mvits_obl_kick.f -o objects/mvits_obl_kick.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_rotate.f -o objects/mvits_rotate.o"; $FORTRAN $FFLAGS ./mvits/mvits_rotate.f -o objects/mvits_rotate.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_rstep_tp.f -o objects/mvits_rstep_tp.o"; $FORTRAN $FFLAGS ./mvits/mvits_rstep_tp.f -o objects/mvits_rstep_tp.o
echo "$FORTRAN $FFLAGS ./mvits/mvits_step.f -o objects/mvits_step.o"; $FORTRAN $FFLAGS ./mvits/mvits_step.f -o objects/mvits_step.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift.f -o objects/drift.o"; $FORTRAN $FFLAGS ./mvs/drift/drift.f -o objects/drift.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_dan.f -o objects/drift_dan.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_dan.f -o objects/drift_dan.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepmd.f -o objects/drift_kepmd.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepmd.f -o objects/drift_kepmd.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu.f -o objects/drift_kepu.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu.f -o objects/drift_kepu.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_fchk.f -o objects/drift_kepu_fchk.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_fchk.f -o objects/drift_kepu_fchk.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_guess.f -o objects/drift_kepu_guess.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_guess.f -o objects/drift_kepu_guess.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_lag.f -o objects/drift_kepu_lag.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_lag.f -o objects/drift_kepu_lag.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_new.f -o objects/drift_kepu_new.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_new.f -o objects/drift_kepu_new.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_p3solve.f -o objects/drift_kepu_p3solve.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_p3solve.f -o objects/drift_kepu_p3solve.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_kepu_stumpff.f -o objects/drift_kepu_stumpff.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_kepu_stumpff.f -o objects/drift_kepu_stumpff.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_one.f -o objects/drift_one.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_one.f -o objects/drift_one.o
echo "$FORTRAN $FFLAGS ./mvs/drift/drift_tp.f -o objects/drift_tp.o"; $FORTRAN $FFLAGS ./mvs/drift/drift_tp.f -o objects/drift_tp.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch.f -o objects/getacch.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch.f -o objects/getacch.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ah0.f -o objects/getacch_ah0.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ah0.f -o objects/getacch_ah0.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ah1.f -o objects/getacch_ah1.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ah1.f -o objects/getacch_ah1.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ah2.f -o objects/getacch_ah2.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ah2.f -o objects/getacch_ah2.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ah3.f -o objects/getacch_ah3.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ah3.f -o objects/getacch_ah3.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ah3_tp.f -o objects/getacch_ah3_tp.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ah3_tp.f -o objects/getacch_ah3_tp.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_ir3.f -o objects/getacch_ir3.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_ir3.f -o objects/getacch_ir3.o
echo "$FORTRAN $FFLAGS ./mvs/getacch/getacch_tp.f -o objects/getacch_tp.o"; $FORTRAN $FFLAGS ./mvs/getacch/getacch_tp.f -o objects/getacch_tp.o
echo "$FORTRAN $FFLAGS ./mvs/kickvh/kickvh.f -o objects/kickvh.o"; $FORTRAN $FFLAGS ./mvs/kickvh/kickvh.f -o objects/kickvh.o
echo "$FORTRAN $FFLAGS ./mvs/kickvh/kickvh_tp.f -o objects/kickvh_tp.o"; $FORTRAN $FFLAGS ./mvs/kickvh/kickvh_tp.f -o objects/kickvh_tp.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_dkd.f -o objects/step_dkd.o"; $FORTRAN $FFLAGS ./mvs/step/step_dkd.f -o objects/step_dkd.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_dkd_pl.f -o objects/step_dkd_pl.o"; $FORTRAN $FFLAGS ./mvs/step/step_dkd_pl.f -o objects/step_dkd_pl.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_dkd_tp.f -o objects/step_dkd_tp.o"; $FORTRAN $FFLAGS ./mvs/step/step_dkd_tp.f -o objects/step_dkd_tp.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_kdk.f -o objects/step_kdk.o"; $FORTRAN $FFLAGS ./mvs/step/step_kdk.f -o objects/step_kdk.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_kdk_pl.f -o objects/step_kdk_pl.o"; $FORTRAN $FFLAGS ./mvs/step/step_kdk_pl.f -o objects/step_kdk_pl.o
echo "$FORTRAN $FFLAGS ./mvs/step/step_kdk_tp.f -o objects/step_kdk_tp.o"; $FORTRAN $FFLAGS ./mvs/step/step_kdk_tp.f -o objects/step_kdk_tp.o
echo "$FORTRAN $FFLAGS ./obl/obl_acc.f -o objects/obl_acc.o"; $FORTRAN $FFLAGS ./obl/obl_acc.f -o objects/obl_acc.o
echo "$FORTRAN $FFLAGS ./obl/obl_acc_tp.f -o objects/obl_acc_tp.o"; $FORTRAN $FFLAGS ./obl/obl_acc_tp.f -o objects/obl_acc_tp.o
echo "$FORTRAN $FFLAGS ./obl/obl_pot.f -o objects/obl_pot.o"; $FORTRAN $FFLAGS ./obl/obl_pot.f -o objects/obl_pot.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_eget.f -o objects/orbel_eget.o"; $FORTRAN $FFLAGS ./orbel/orbel_eget.f -o objects/orbel_eget.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_ehie.f -o objects/orbel_ehie.o"; $FORTRAN $FFLAGS ./orbel/orbel_ehie.f -o objects/orbel_ehie.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_ehybrid.f -o objects/orbel_ehybrid.o"; $FORTRAN $FFLAGS ./orbel/orbel_ehybrid.f -o objects/orbel_ehybrid.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_el2xv.f -o objects/orbel_el2xv.o"; $FORTRAN $FFLAGS ./orbel/orbel_el2xv.f -o objects/orbel_el2xv.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_esolmd.f -o objects/orbel_esolmd.o"; $FORTRAN $FFLAGS ./orbel/orbel_esolmd.f -o objects/orbel_esolmd.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_fget.f -o objects/orbel_fget.o"; $FORTRAN $FFLAGS ./orbel/orbel_fget.f -o objects/orbel_fget.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_fhybrid.f -o objects/orbel_fhybrid.o"; $FORTRAN $FFLAGS ./orbel/orbel_fhybrid.f -o objects/orbel_fhybrid.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_flon.f -o objects/orbel_flon.o"; $FORTRAN $FFLAGS ./orbel/orbel_flon.f -o objects/orbel_flon.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_scget.f -o objects/orbel_scget.o"; $FORTRAN $FFLAGS ./orbel/orbel_scget.f -o objects/orbel_scget.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_schget.f -o objects/orbel_schget.o"; $FORTRAN $FFLAGS ./orbel/orbel_schget.f -o objects/orbel_schget.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_xv2aeq.f -o objects/orbel_xv2aeq.o"; $FORTRAN $FFLAGS ./orbel/orbel_xv2aeq.f -o objects/orbel_xv2aeq.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_xv2el.f -o objects/orbel_xv2el.o"; $FORTRAN $FFLAGS ./orbel/orbel_xv2el.f -o objects/orbel_xv2el.o
echo "$FORTRAN $FFLAGS ./orbel/orbel_zget.f -o objects/orbel_zget.o"; $FORTRAN $FFLAGS ./orbel/orbel_zget.f -o objects/orbel_zget.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_chk.f -o objects/rmvs_chk.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_chk.f -o objects/rmvs_chk.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_chk_ind.f -o objects/rmvs_chk_ind.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_chk_ind.f -o objects/rmvs_chk_ind.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_elog.f -o objects/rmvs_elog.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_elog.f -o objects/rmvs_elog.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_obl_acc.f -o objects/rmvs_obl_acc.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_obl_acc.f -o objects/rmvs_obl_acc.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_peri.f -o objects/rmvs_peri.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_peri.f -o objects/rmvs_peri.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_step.f -o objects/rmvs_step.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_step.f -o objects/rmvs_step.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_step_in.f -o objects/rmvs_step_in.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_step_in.f -o objects/rmvs_step_in.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_step_in_mvpl.f -o objects/rmvs_step_in_mvpl.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_step_in_mvpl.f -o objects/rmvs_step_in_mvpl.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_step_in_tp.f -o objects/rmvs_step_in_tp.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_step_in_tp.f -o objects/rmvs_step_in_tp.o
echo "$FORTRAN $FFLAGS ./rmvs/rmvs_step_out.f -o objects/rmvs_step_out.o"; $FORTRAN $FFLAGS ./rmvs/rmvs_step_out.f -o objects/rmvs_step_out.o
echo "$FORTRAN $FFLAGS ./rmvs2/rmvs2_interp.f -o objects/rmvs2_interp.o"; $FORTRAN $FFLAGS ./rmvs2/rmvs2_interp.f -o objects/rmvs2_interp.o
echo "$FORTRAN $FFLAGS ./rmvs2/rmvs2_interp_o.f -o objects/rmvs2_interp_o.o"; $FORTRAN $FFLAGS ./rmvs2/rmvs2_interp_o.f -o objects/rmvs2_interp_o.o
echo "$FORTRAN $FFLAGS ./rmvs2/rmvs2_step.f -o objects/rmvs2_step.o"; $FORTRAN $FFLAGS ./rmvs2/rmvs2_step.f -o objects/rmvs2_step.o
echo "$FORTRAN $FFLAGS ./rmvs2/rmvs2_step_out.f -o objects/rmvs2_step_out.o"; $FORTRAN $FFLAGS ./rmvs2/rmvs2_step_out.f -o objects/rmvs2_step_out.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_chk.f -o objects/rmvs3_chk.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_chk.f -o objects/rmvs3_chk.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_elog.f -o objects/rmvs3_elog.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_elog.f -o objects/rmvs3_elog.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_interp.f -o objects/rmvs3_interp.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_interp.f -o objects/rmvs3_interp.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_step.f -o objects/rmvs3_step.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_step.f -o objects/rmvs3_step.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_step_in.f -o objects/rmvs3_step_in.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_step_in.f -o objects/rmvs3_step_in.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_step_out.f -o objects/rmvs3_step_out.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_step_out.f -o objects/rmvs3_step_out.o
echo "$FORTRAN $FFLAGS ./rmvs3/rmvs3_step_out2.f -o objects/rmvs3_step_out2.o"; $FORTRAN $FFLAGS ./rmvs3/rmvs3_step_out2.f -o objects/rmvs3_step_out2.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_getaccb.f -o objects/tu4_getaccb.o"; $FORTRAN $FFLAGS ./tu4/tu4_getaccb.f -o objects/tu4_getaccb.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_getaccb_tp.f -o objects/tu4_getaccb_tp.o"; $FORTRAN $FFLAGS ./tu4/tu4_getaccb_tp.f -o objects/tu4_getaccb_tp.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_ldrift.f -o objects/tu4_ldrift.o"; $FORTRAN $FFLAGS ./tu4/tu4_ldrift.f -o objects/tu4_ldrift.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_ldrift_tp.f -o objects/tu4_ldrift_tp.o"; $FORTRAN $FFLAGS ./tu4/tu4_ldrift_tp.f -o objects/tu4_ldrift_tp.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_step.f -o objects/tu4_step.o"; $FORTRAN $FFLAGS ./tu4/tu4_step.f -o objects/tu4_step.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_vkickb.f -o objects/tu4_vkickb.o"; $FORTRAN $FFLAGS ./tu4/tu4_vkickb.f -o objects/tu4_vkickb.o
echo "$FORTRAN $FFLAGS ./tu4/tu4_vkickb_tp.f -o objects/tu4_vkickb_tp.o"; $FORTRAN $FFLAGS ./tu4/tu4_vkickb_tp.f -o objects/tu4_vkickb_tp.o
echo "$FORTRAN $FFLAGS ./util/util_exit.f -o objects/util_exit.o"; $FORTRAN $FFLAGS ./util/util_exit.f -o objects/util_exit.o
echo "$FORTRAN $FFLAGS ./util/util_hills.f -o objects/util_hills.o"; $FORTRAN $FFLAGS ./util/util_hills.f -o objects/util_hills.o
echo "$FORTRAN $FFLAGS ./util/util_hills1.f -o objects/util_hills1.o"; $FORTRAN $FFLAGS ./util/util_hills1.f -o objects/util_hills1.o
echo "$FORTRAN $FFLAGS ./util/util_mass_peri.f -o objects/util_mass_peri.o"; $FORTRAN $FFLAGS ./util/util_mass_peri.f -o objects/util_mass_peri.o
echo "$FORTRAN $FFLAGS ./util/util_peri.f -o objects/util_peri.o"; $FORTRAN $FFLAGS ./util/util_peri.f -o objects/util_peri.o
echo "$FORTRAN $FFLAGS ./util/util_version.f -o objects/util_version.o"; $FORTRAN $FFLAGS ./util/util_version.f -o objects/util_version.o
ar ruv libswift.a objects/*.o
ar ts libswift.a
