extern char * ok_orb_labels[13];
extern char * ok_all_orb_labels[20];
typedef struct ok_system {
        int nplanets;
            double epoch;
                    gsl_matrix* elements;
            double time;
            gsl_matrix* xyz;
            gsl_matrix* orbits;
        int flag;
} ok_system;
typedef struct ok_kernel ok_kernel;
typedef double(*ok_callback)(ok_kernel*);
typedef void(*ok_callback2)(ok_kernel*, double*);
typedef void(*ok_icallback)(int);
typedef int(*ok_progress)(int current, int max, void* state, const char* function);
typedef struct ok_integrator_options {
        double abs_acc;
    double rel_acc;
        double acc_par;
        double dt;
        double eps_tr;
    int iterations;
    bool calc_elements;
                int (* force) (double, const double[], double[], void*);
    int (* jac) (double, const double[], double*, double[], void*);
    int (* force_jerk) (double, const double[], double[], double[], void*);
            gsl_vector* buffer;
    gsl_vector_int* ibuffer;
    ok_progress progress;
} ok_integrator_options;
typedef void(*ok_model_function)(ok_kernel*, double** data, int ndata);
typedef ok_system**(*ok_integrator)(ok_system*, const gsl_vector*, ok_integrator_options*, ok_system** bag);
typedef int(*ok_minimizer)(ok_kernel*, int, double[]);
struct ok_kernel {
        ok_system* system;
        double chi2;
        double chi2_rvs;
        double chi2_tts;
        double chi2_other;
        double rms;
        double rms_tts;
        double jitter;
        int nsets;
        gsl_matrix** datasets;
            double** compiled;
        gsl_vector* params;
        gsl_vector* times;
        ok_system** integration;
        int integrationSamples;
        gsl_matrix_int* plFlags;
    gsl_vector_int* parFlags;
    gsl_matrix* plSteps;
    gsl_vector* parSteps;
    gsl_matrix** plRanges;
    gsl_vector** parRanges;
        double Mstar;
        int ndata;
    int nrvs;
    int ntts;
    int nrpars;
        int intMethod;
    ok_integrator_options* intOptions;
        ok_callback minfunc;
        unsigned int flags;
        gsl_rng* rng;
        void* tag;
    double tagValue;
        ok_progress progress;
        char datanames[10][8192];
        ok_model_function model_function;
    int last_error;
};
typedef struct ok_list_item {
    gsl_matrix* elements;
    gsl_vector* params;
    double merit;
    double merit_pr;
    double merit_li;
    int tag;
} ok_list_item;
typedef struct ok_list {
    ok_kernel* prototype;
    ok_list_item** kernels;
    int size;
    void* diags;
    int type;
} ok_list;
typedef struct ok_kernel_minimizer_pars {
    double** pars;
    double* steps;
    double* min;
    double* max;
    int* type;
    int npars;
} ok_kernel_minimizer_pars;
typedef struct {
    void* data;
    int tag[5];
} ok_tagdata;
double DEGRANGE(double angle);
double RADRANGE(double angle);
void ok_sort_small_matrix(gsl_matrix* matrix, const int column);
void ok_sort_matrix(gsl_matrix* matrix, const int column);
void ok_rsort_matrix(gsl_matrix* matrix, const int column);
void ok_fprintf_matrix(gsl_matrix* matrix, FILE* file, const char* format);
void ok_fprintf_vector(gsl_vector* v, FILE* file, const char* format);
void ok_fprintf_matrix_int(gsl_matrix_int* matrix, FILE* file, const char* format);
void ok_fprintf_vector_int(gsl_vector_int* v, FILE* file, const char* format);
void ok_fprintf_buf(double** buf, FILE* file, const char* format, int rows, int columns);
void ok_fscanf_matrix(gsl_matrix* matrix, FILE* file);
void ok_fscanf_matrix_int(gsl_matrix_int* matrix, FILE* file);
void ok_fscanf_vector(gsl_vector* matrix, FILE* file);
void ok_fscanf_vector_int(gsl_vector_int* matrix, FILE* file);
bool ok_save_matrix(gsl_matrix* matrix, FILE* fid, const char* format);
bool ok_save_matrix_bin(gsl_matrix* matrix, FILE* fid);
bool ok_save_buf(double** matrix, FILE* fid, const char* format, int rows, int cols);
bool ok_save_buf_bin(double** matrix, FILE* fid, int rows, int cols);
gsl_matrix* ok_read_table(FILE* fid);
gsl_vector* ok_vector_resize(gsl_vector* v, int len);
gsl_matrix* ok_matrix_resize(gsl_matrix* v, int rows, int cols);
gsl_vector* ok_vector_resize_pad(gsl_vector* v, int len, double pad);
gsl_matrix* ok_matrix_resize_pad(gsl_matrix* v, int rows, int cols, double pad);
gsl_vector_int* ok_vector_int_resize(gsl_vector_int* v, int len);
gsl_matrix_int* ok_matrix_int_resize(gsl_matrix_int* v, int rows, int cols);
gsl_matrix* ok_matrix_copy(const gsl_matrix* src);
gsl_matrix* ok_matrix_copy_sub(const gsl_matrix* src, int row1, int nrows, int col1, int ncols);
gsl_matrix_int* ok_matrix_int_copy(const gsl_matrix_int* src);
gsl_vector* ok_vector_copy(const gsl_vector* src);
gsl_vector_int* ok_vector_int_copy(const gsl_vector_int* src);
gsl_matrix* ok_buf_to_matrix(double** buf, int rows, int cols);
void ok_buf_col(double** buf, double* vector, int col, int nrows);
gsl_matrix* ok_matrix_remove_row(gsl_matrix* m, int row);
gsl_matrix* ok_matrix_remove_column(gsl_matrix* m, int col);
gsl_matrix_int* ok_matrix_int_remove_row(gsl_matrix_int* m, int row);
gsl_matrix_int* ok_matrix_int_remove_column(gsl_matrix_int* m, int col);
gsl_vector* ok_vector_remove(gsl_vector* m, int idx);
gsl_vector_int* ok_vector_int_remove(gsl_vector_int* m, int idx);
void ok_matrix_fill(gsl_matrix* src, gsl_matrix* dest);
void ok_bootstrap_matrix(const gsl_matrix* matrix, gsl_matrix* out, const int sortcol, gsl_rng* r);
void ok_bootstrap_matrix_mean(const gsl_matrix* matrix, int timecol, int valcol, gsl_matrix* out, gsl_rng* r);
gsl_matrix* ok_matrix_filter(gsl_matrix* matrix, const int column, const double filter);
gsl_matrix* ok_matrix_buf_filter(double** matrix, const int rows, const int columns, const int column, const double filter);
int ok_bsearch(double* v, double val, int len);
double ok_average_angle(const double* v, const int length, const bool isRadians);
double ok_median_angle(const double* v, const int length, const bool isRadians);
double ok_stddev_angle(const double* v, const int length, const bool isRadians);
double ok_mad_angle(double* v, const int length, const double med, const bool isRadians);
double ok_mad(double* v, const int length, const double med);
char* ok_str_copy(const char* src);
char* ok_str_cat(const char* a1, const char* a2);
void ok_avevar(const double* v, int len, double* ave, double* var);
gsl_matrix* ok_ptr_to_matrix(double* v, unsigned int rows, unsigned int cols);
gsl_vector* ok_ptr_to_vector(double* v, unsigned int len);
gsl_matrix_int* ok_iptr_to_imatrix(int* v, unsigned int rows, unsigned int cols);
gsl_vector_int* ok_iptr_to_ivector(int* v, unsigned int len);
void ok_block_to_ptr(void* vv, double* out);
void ok_buf_to_ptr(double** v, unsigned int rows, unsigned int cols, double* out);
void ok_buf_add_to_col(double** buf, double* col_vector, int col, int nrows);
unsigned int ok_vector_len(void* v);
unsigned int ok_matrix_rows(void* v);
unsigned int ok_matrix_cols(void* v);
gsl_block* ok_vector_block(void* v);
gsl_block* ok_matrix_block(void* v);
gsl_matrix* ok_resample_curve(gsl_matrix* curve, int timecol, int valcol, int every, double top);
bool ok_file_readable(char* fn);
extern double ok_default_steps[];
ok_kernel* K_alloc();
void K_free(ok_kernel* k);
ok_kernel* K_clone(ok_kernel* k);
ok_kernel* K_cloneFlags(ok_kernel* k, unsigned int shareFlags);
gsl_matrix* K_addDataFile(ok_kernel* k, const char* path, int type);
gsl_matrix* K_addDataTable(ok_kernel* k, gsl_matrix* rvtable, const char* name, int type);
void K_removeData(ok_kernel* k, int idx);
gsl_matrix* K_getData(ok_kernel* k, int idx);
void K_setData(ok_kernel* k, int idx, gsl_matrix* data);
const char* K_getDataName(ok_kernel* k, int idx);
bool K_addDataFromSystem(ok_kernel* k, const char* filename);
int K_getDataType(ok_kernel* k, int idx);
int K_getDataSize(ok_kernel* k, int idx);
double** K_compileData(ok_kernel* k);
gsl_matrix* K_getCompiledDataMatrix(ok_kernel* k);
void K_addPlanet(ok_kernel* k, const double elements[]);
void K_removePlanet(ok_kernel* k, int idx);
void K_setElement(ok_kernel* k, int row, int col, double value);
double K_getElement(ok_kernel* k, int row, int col);
void K_setElements(ok_kernel* k, gsl_matrix* elements);
gsl_matrix* K_getElements(ok_kernel* k);
void K_setElementFlag(ok_kernel* k, int row, int col, int value);
int K_getElementFlag(ok_kernel* k, int row, int col);
void K_setElementStep(ok_kernel* k, int row, int col, double value);
double K_getElementStep(ok_kernel* k, int row, int col);
void K_setElementRange(ok_kernel* k, int row, int col, double min, double max);
void K_getElementRange(ok_kernel* k, int row, int col, double* min, double* max);
gsl_matrix* K_getAllElements(ok_kernel* k);
int K_getActivePars(ok_kernel* k);
int K_getActiveElements(ok_kernel* k);
int K_getNrPars(ok_kernel* k);
void K_setElementType(ok_kernel* k, int type);
int K_getElementType(ok_kernel* k);
gsl_matrix* K_getXYZ(ok_kernel* k);
void K_setMstar(ok_kernel* k, double value); double K_getMstar(ok_kernel* k);
void K_setEpoch(ok_kernel* k, double value); double K_getEpoch(ok_kernel* k);
double K_getChi2(ok_kernel* k);
double K_getChi2_nr(ok_kernel* k);
double K_getLoglik(ok_kernel* k);
double K_getRms(ok_kernel* k);
double K_getJitter(ok_kernel* k);
double** K_getCompiled(ok_kernel* k);
unsigned int K_getNrvs(ok_kernel* k);
unsigned int K_getNtts(ok_kernel* k);
unsigned int K_getNsets(ok_kernel* k);
double K_getChi2_rvs(ok_kernel* k);
double K_getChi2_tts(ok_kernel* k);
double K_getRms_tts(ok_kernel* k);
void K_setFlags(ok_kernel* k, unsigned int value); unsigned int K_getFlags(ok_kernel* k);
void K_setMinFunc(ok_kernel* k, ok_callback value); ok_callback K_getMinFunc(ok_kernel* k);
void K_setElementSteps(ok_kernel* k, gsl_matrix* value); gsl_matrix* K_getElementSteps(ok_kernel* k);
void K_setParSteps(ok_kernel* k, gsl_vector* value); gsl_vector* K_getParSteps(ok_kernel* k);
void K_setElementFlags(ok_kernel* k, gsl_matrix_int* value); gsl_matrix_int* K_getElementFlags(ok_kernel* k);
void K_setParFlags(ok_kernel* k, gsl_vector_int* value); gsl_vector_int* K_getParFlags(ok_kernel* k);
void K_setIntMethod(ok_kernel* k, int value); int K_getIntMethod(ok_kernel* k);
void K_setProgress(ok_kernel* k, ok_progress value); ok_progress K_getProgress(ok_kernel* k);
void K_setIntOptions(ok_kernel* k, ok_integrator_options* value); ok_integrator_options* K_getIntOptions(ok_kernel* k);
void K_setCustomModelFunction(ok_kernel* k, ok_model_function value); ok_model_function K_getCustomModelFunction(ok_kernel* k);
void K_setIntAbsAcc(ok_kernel* k, double value); double K_getIntAbsAcc(ok_kernel* k);
void K_setIntRelAcc(ok_kernel* k, double value); double K_getIntRelAcc(ok_kernel* k);
void K_setIntDt(ok_kernel* k, double value); double K_getIntDt(ok_kernel* k);
unsigned int K_getNplanets(ok_kernel* k);
unsigned int K_getNdata(ok_kernel* k);
void K_getRange(ok_kernel* k, double* from, double* to);
void K_perturb(ok_kernel* k);
void K_setPars(ok_kernel* k, gsl_vector* pars);
gsl_vector* K_getPars(ok_kernel* k);
void K_setPar(ok_kernel* k, int idx, double val);
double K_getPar(ok_kernel* k, int idx);
void K_setParFlag(ok_kernel* k, int idx, int value);
int K_getParFlag(ok_kernel* k, int idx);
void K_setParStep(ok_kernel* k, int idx, double value);
double K_getParStep(ok_kernel* k, int idx);
void K_setParRange(ok_kernel* k, int idx, double min, double max);
void K_getParRange(ok_kernel* k, int idx, double* min, double* max);
bool K_save(ok_kernel* k, FILE* fid);
ok_kernel* K_load(FILE* fid, int skip);
bool K_addDataFromSystem(ok_kernel* k, const char* filename);
void K_calculate(ok_kernel* k);
int K_minimize(ok_kernel* k, int algo, int maxiter, double params[]);
int K_1dminimize(ok_kernel* k, int algo, int maxiter, int row, int column, double params[]);
ok_system** K_integrate(ok_kernel* k, gsl_vector* times, ok_system** bag, int* error);
ok_system** K_integrateRange(ok_kernel* k, double from, double to, unsigned int samples, ok_system** bag, int* error);
gsl_matrix* K_integrateStellarVelocity(ok_kernel* k, double from, double to, unsigned int samples, ok_system** bag, int* error);
ok_system** K_integrateProgress(ok_kernel* k, gsl_vector* times, ok_system** bag, int* error);
void K_print(ok_kernel* k, FILE* f);
void K_save_old(ok_kernel* k, const char* stem);
void K_setSeed(ok_kernel* k, unsigned long int seed);
void* ok_bridge_kernel_buf(void* buf, int n, ok_kernel* k);
extern double ok_min_distance;
extern ok_integrator_options defoptions;
ok_system* ok_alloc_system(int nplanets);
void ok_free_system(ok_system* system);
void ok_free_systems(ok_system** system, unsigned int len);
ok_system* ok_copy_system(const ok_system* orig);
void ok_resize_system(ok_system* system, int npnew);
void ok_el2cart(ok_system* system, gsl_matrix* xyz);
void ok_cart2el(ok_system* system, gsl_matrix* els, bool internal);
void ok_setup(ok_system* system);
int ok_force(double t, const double y[], double f[], void *params);
int ok_jac(double t, const double y[], double *dfdy,
    double dfdt[], void *params);
ok_system** ok_integrate(ok_system* initial, const gsl_vector* times, ok_integrator_options* options, const int integrator,
        ok_system** bag, int* error);
double ok_get_rv(ok_system* sys);
gsl_matrix* ok_get_rvs(ok_system** sys, int len);
gsl_matrix* ok_get_xyzs(ok_system** bag, int len);
gsl_matrix* ok_get_els(ok_system** bag, int len, bool internal);
gsl_vector* ok_find_transits(ok_system** bag, const int len, const int pidx, const int intMethod, const double eps, const int flags[], int* error);
void ok_to_cm(ok_system* system, gsl_matrix* xyz);
void ok_to_star(ok_system* system, gsl_matrix* xyz);
int ok_find_closest_transit(ok_system* sys, const int pidx, ok_integrator_options* options, const int intMethod, const double eps, const int type, double* timeout, int* error);
double ok_pcalc(const double a, const double Mcenter, const double Mp);
double ok_acalc(const double P, const double Mcenter, const double Mp);
    ok_list* KL_alloc(const int size, ok_kernel* prototype);
    void KL_free(ok_list* list);
    ok_list* KL_load(FILE* fid, int skip);
    void KL_save(const ok_list* kl, FILE* out);
    void KL_append(ok_list* dest, ok_list* src);
    gsl_vector* KL_getParsStats(const ok_list* kl, const int what);
    gsl_vector* KL_getElements(const ok_list* kl, const int pl, const int el);
    gsl_vector* KL_getPars(const ok_list* kl, const int vo);
    gsl_matrix* KL_getElementsStats(const ok_list* kl, const int what);
    ok_list_item* KL_set(ok_list* kl, const int idx, gsl_matrix* elements, gsl_vector* pars, double merit, int tag);
    int KL_getSize(const ok_list* kl);
    void KL_removeAtIndex(ok_list* kl, const int idx);
    void KL_fprintf(const ok_list* kl, FILE* out, const char* fmt, const char* lfmt);
    void KL_to_ptr(const ok_list* kl, double* out);
    int KL_getNplanets(const ok_list* kl);
ok_list* K_mcmc_single(ok_kernel* k, unsigned int nsteps, unsigned int skip, unsigned int discard, const double dparams[], ok_list* cont, ok_callback2 merit_function, int tag, int* flag);
ok_list* K_mcmc_mult(ok_kernel** k, unsigned int nchains, unsigned int ntemps, unsigned int skip, unsigned int discard, const double params[], double Rstop, ok_callback2 merit_function);
    ok_list* K_bootstrap(ok_kernel* k, int trials, int warmup, int malgo, int miter, double mparams[]);
    typedef struct {
        double W;
        double zmax;
        double z2max;
        double fapmax;
        double z_fap_1;
        double z_fap_2;
        double z_fap_3;
        bool calc_z_fap;
        gsl_matrix* per;
        gsl_matrix* buf;
        gsl_vector* zm;
    } ok_periodogram_workspace;
    gsl_matrix* ok_periodogram_ls(const gsl_matrix* data, const unsigned int samples, const double Pmin, const double Pmax, const int method,
        unsigned int timecol, unsigned int valcol, unsigned int sigcol, ok_periodogram_workspace* p);
    gsl_matrix* ok_periodogram_boot(const gsl_matrix* data, const unsigned int trials, const unsigned int samples,
        const double Pmin, const double Pmax, const int method,
        const unsigned int timecol, const unsigned int valcol, const unsigned int sigcol,
        const unsigned long int seed, ok_periodogram_workspace* p, ok_progress prog);
    gsl_matrix* ok_periodogram_full(ok_kernel* k, int type, int algo, bool circular, unsigned int sample,
        const unsigned int samples, const double Pmin, const double Pmax);
    int K_isMstable_coplanar(const gsl_matrix* alle);
    double K_crossval_l1o(ok_kernel* k, int minalgo, int maxiter, double params[]);
int mco_el2x__(doublereal mu, doublereal q, doublereal e,
               doublereal i__, doublereal p, doublereal n, doublereal l,
               doublereal* x, doublereal* y, doublereal* z__, doublereal* u,
               doublereal* v, doublereal* w);
int mco_x2el__(doublereal* mu, doublereal* x, doublereal* y,
               doublereal* z__, doublereal* u, doublereal* v, doublereal* w,
               doublereal* q, doublereal* e, doublereal* i__, doublereal* p,
               doublereal* n, doublereal* l);
doublereal mco_kep__(doublereal e, doublereal oldl);dyn.load("libsystemic.dylib")
gsl_matrix* gsl_matrix_alloc(size_t n1, size_t n2);
gsl_matrix* gsl_matrix_calloc(size_t n1, size_t n2);
void gsl_matrix_free(gsl_matrix* m);
void gsl_vector_free(gsl_vector* v);
int gsl_matrix_fwrite(FILE* stream, const gsl_matrix* m);
int gsl_matrix_fread(FILE* stream, gsl_matrix* m);
int gsl_matrix_fprintf(FILE* stream, const gsl_matrix* m, const char* format);
int gsl_matrix_fscanf(FILE* stream, gsl_matrix* m);
double gsl_matrix_get(const gsl_matrix* m, size_t i, size_t j);
void gsl_matrix_set(gsl_matrix* m, size_t i, size_t j, double x);
void free(void* v);
FILE* fopen(const char* filename, const char* mode);
int fclose(FILE* stream);
size_t fwrite(const void* ptr, size_t size, size_t count, FILE* stream);
int fputs(const char* str, FILE* stream);
