install.packages('bitops', repos="http://cran.us.r-project.org")
install.packages('gdata', repos="http://cran.us.r-project.org")
install.packages('gplots', repos="http://cran.us.r-project.org")
install.packages('circular', repos="http://cran.us.r-project.org")
install.packages('checkmate', repos="http://cran.us.r-project.org")
install.packages('survival', repos="http://cran.us.r-project.org")
install.packages('Hmisc', repos="http://cran.us.r-project.org")
install.packages('MASS', repos="http://cran.us.r-project.org")
install.packages('KernSmooth', repos="http://cran.us.r-project.org")
install.packages('R/rdyncall_0.7.5.tgz', repos = NULL, type="source")